version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: planner_db
    ports:
      - "3316:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=planner_db

